testsuite Context-sensitive pointer analysis with 1 object calling context

test The item field of Container can point to all allocations of Item
  using database tests/context/ContainerTest1.jar
    ->
  InstanceFieldPointsTo(?h, "<Container: Item item>", "ContainerTest1.main/new Container/0")
    ->
  "ContainerTest1.main/new Item/0"

test The item field of Container can point to all allocations of Item
  using database tests/context/ContainerTest1.jar
    ->
  InstanceFieldPointsTo(?h, "<Container: Item item>", "ContainerTest1.main/new Container/1")
    ->
  "ContainerTest1.main/new Item/1"

test The item field of Container can point to all allocations of Item
  using database tests/context/ContainerTest2.jar
    ->
  InstanceFieldPointsTo(?h, "<Container: Item item>", "ContainerTest2.main/new Container/0")
    ->
  "Container.<init>/new Item/0"
  "ContainerTest2.main/new Item/0"

test The item field of Container can point to all allocations of Item
  using database tests/context/ContainerTest2.jar
    ->
  InstanceFieldPointsTo(?h, "<Container: Item item>", "ContainerTest2.main/new Container/1")
    ->
  "Container.<init>/new Item/0"
  "ContainerTest2.main/new Item/1"

test Example requiring object sensitive analysis or 2-call-site (not 1-call-site)
  using database tests/context/ContainerTest3.jar
    ->
  InstanceFieldPointsTo(?h, "<Container: Item item>", "ContainerTest3.main/new Container/0")
    ->
  "ContainerTest3.main/new Item/0"

test Example requiring object sensitive analysis or 2-call-site  (not 1-call-site)
  using database tests/context/ContainerTest3.jar
    ->
  InstanceFieldPointsTo(?h, "<Container: Item item>", "ContainerTest3.main/new Container/1")
    ->
  "ContainerTest3.main/new Item/1"

/**
 * JVM Start-up
 */
test ClassLoader constructor
  using database tests/Reachable.jar
  assert
    ImplicitReachable("<java.lang.ClassLoader: void <init>()>")
    Reachable("<java.lang.ClassLoader: void <init>()>")
    ReachableContext("<<jvm-startup>>", "<java.lang.ClassLoader: void <init>()>")

test ThreadGroup constructor
  using database tests/Reachable.jar
  assert
    Reachable("<java.lang.ThreadGroup: void <init>()>")

test ThreadGroup constructor is invoked in context of system-thread-group
  using database tests/Reachable.jar
  assert
    ReachableContext("<<system-thread-group>>", "<java.lang.ThreadGroup: void <init>()>")

/**
 * Exceptions
 */
test Method without any thrown exceptions (Test1)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "Exceptions.main/Test1.test/0", "<Test1: void test()>")
    ->
  empty

test Method directly throwing an exception (Test2)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test2: void test()>")
    ->
  "Test2.test/new java.lang.Exception/0"

test Method indirectly throwing an exception (Test3)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test3: void test()>")
    ->
  "Test3.helper/new java.lang.Exception/0"

test Method indirectly throwing two exceptions (Test4)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test4: void test()>")
    ->
  "Test4.helper1/new java.lang.Exception/0"
  "Test4.helper2/new java.lang.Exception/0"

test Method indirectly throwing two exceptions (Test5)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test5: void test()>")
    ->
  "Test5.helper1/new java.lang.Exception/0"
  "Test5.helper2/new java.lang.Exception/0"

test Method indirectly throwing an exception via a constructor call (Test6)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test6: void test()>")
    ->
  "Test6.<init>/new java.lang.Exception/0"

test Method indirectly throwing an exception via a constructor call (Test6, sanity check)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "Test6.test/new Test6/0", "<Test6: void <init>()>")
    ->
  "Test6.<init>/new java.lang.Exception/0"

test Method indirectly throwing an exception via a virtual call (Test7)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test7: void test()>")
    ->
  "Test7.helper/new java.lang.Exception/0"

test Method indirectly throwing an exception via a virtual call (Test7, sanity check)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "Test7.test/new Test7/0", "<Test7: void helper()>")
    ->
  "Test7.helper/new java.lang.Exception/0"

test Method catching all exceptions (Test8a)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test8a: void test()>")
    ->
  empty

test Method catching all exceptions (Test8a, sanity check)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test8a: void helper()>")
    ->
  "Test8a.helper/new java.lang.Exception/0"

test Method catching all exceptions (Test8b)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test8b: void test()>")
    ->
  empty

test Method catching all exceptions (Test8b, sanity check)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test8b: void helper()>")
    ->
  "Test8b.helper/new java.lang.Exception/0"

test Method catching all exceptions (Test8b, sanity check)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test8b: void helper()>")
    ->
  "Test8b.helper/new java.lang.Exception/0"

test Method catching all exceptions (Test8c)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test8c: void test()>")
    ->
  empty

test Method catching all exceptions (Test8c, sanity check)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test8c: void helper1()>")
    ->
  "Test8c.helper1/new java.lang.Exception/0"

test Method catching all exceptions (Test8c, sanity check)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test8c: void helper2()>")
    ->
  "Test8c.helper2/new java.lang.Exception/0"

test Method catching only run-time exceptions (Test9)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test9: void test()>")
    ->
  "Test9.helper/new java.lang.Exception/0"

test Method catching some exceptions (Test10)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test10: void test()>")
    ->
  "Test10.helper2/new java.lang.Exception/0"

test Method catching some exceptions (Test11)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test11: void test()>")
    ->
  "Test11.helper2/new java.lang.Exception/0"

test Method catching all exceptions also catches IOException (Test12)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test12: void test()>")
    ->
  empty

test Method catching all exceptions also catches IOException (Test12, sanity check)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test12: void helper()>")
    ->
  "Test12.helper/new java.io.IOException/0"

test Thrown exception is assigned to formal parameter of handler (Test13)
  using database tests/hello/Exceptions.jar
    ->
  StaticFieldPointsTo(?h, "<Test13: java.lang.Object o>")
    ->
  "Test13.test/new java.lang.Exception/0"

test Thrown exception is caught immediately (Test13, sanity check)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test13: void test()>")
    ->
  empty

test Thrown exception is not caught (Test14)
  using database tests/hello/Exceptions.jar
    ->
  StaticFieldPointsTo(?h, "<Test14: java.lang.Object o>")
    ->
  empty

test Thrown exception is not caught immediately (Test14, sanity check)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test14: void test()>")
    ->
  "Test14.test/new java.lang.Exception/0"

test Thrown exception is assigned to formal parameter of handler (Test15)
  using database tests/hello/Exceptions.jar
    ->
  StaticFieldPointsTo(?h, "<Test15: java.lang.Object o>")
    ->
  "Test15.helper/new java.lang.Exception/0"

test Imprecision of not considering the order of exception handlers (Test16)
  using database tests/hello/Exceptions.jar
    ->
  StaticFieldPointsTo(?h, "<Test16: java.lang.Object o1>")
    ->
  "Test16.test/new java.lang.RuntimeException/0"

test Imprecision of not considering the order of exception handlers (Test16)
  using database tests/hello/Exceptions.jar
    ->
  StaticFieldPointsTo(?h, "<Test16: java.lang.Object o2>")
    ->
  empty

test Imprecision of not considering the order of exception handlers (Test17)
  using database tests/hello/Exceptions.jar
    ->
  ThrowPointsTo(?h, "<<initial-context>>", "<Test17: void test()>")
    ->
  empty
